#include <furi.h>

/* generated by fbt from .png files in images folder, at compile-time */
#include <kyw_icons.h>

// Application entry point
// Your main() equivalent
int32_t kyw_app(void* p) {
    UNUSED(p);

    return 0;
}
